"""Business-day calendars for lag and staleness.

Two calendars, because the spec measures two different things:

- SEC business days (`SEC`) count toward the legal filing deadline. EDGAR is closed on
  federal holidays, including Columbus Day and Veterans Day when markets are open,
  and open on Good Friday when markets are closed. `lag_days` uses this calendar.
- NYSE trading days (`NYSE`) are when prices move and a signal can be traded.
  `days_since_filing` uses this calendar.

Holidays are generated by rule, so any year works. Unscheduled closures (days of
mourning, storms, extra days off by executive order) are listed explicitly.
"""

from datetime import date, timedelta
from functools import lru_cache


def _nth_weekday(year: int, month: int, weekday: int, n: int) -> date:
    """The n-th given weekday (Mon=0) of a month; n=-1 is the last."""
    if n > 0:
        d = date(year, month, 1)
        d += timedelta(days=(weekday - d.weekday()) % 7)
        return d + timedelta(weeks=n - 1)
    d = date(year + (month == 12), month % 12 + 1, 1) - timedelta(days=1)
    return d - timedelta(days=(d.weekday() - weekday) % 7)


def easter(year: int) -> date:
    """Gregorian Easter Sunday (Meeus/Jones/Butcher)."""
    a, b, c = year % 19, year // 100, year % 100
    d, e = b // 4, b % 4
    f = (b + 8) // 25
    g = (b - f + 1) // 3
    h = (19 * a + b - d - g + 15) % 30
    i, k = c // 4, c % 4
    l = (32 + 2 * e + 2 * i - h - k) % 7
    m = (a + 11 * h + 22 * l) // 451
    month = (h + l - 7 * m + 114) // 31
    day = (h + l - 7 * m + 114) % 31 + 1
    return date(year, month, day)


def _observed(d: date) -> date:
    """Saturday holidays move to Friday, Sunday holidays to Monday."""
    if d.weekday() == 5:
        return d - timedelta(days=1)
    if d.weekday() == 6:
        return d + timedelta(days=1)
    return d


# Federal offices closed by proclamation or executive order (SEC included).
FEDERAL_EXTRA = {
    date(2018, 12, 5),   # President George H. W. Bush, day of mourning
    date(2018, 12, 24),  # executive order
    date(2019, 12, 24),  # executive order
    date(2020, 12, 24),  # executive order
    date(2024, 12, 24),  # executive order
    date(2025, 1, 9),    # President Carter, day of mourning
    date(2025, 12, 24),  # executive order
    date(2025, 12, 26),  # executive order
}

# NYSE unscheduled full-day closures.
NYSE_EXTRA = {
    date(2001, 9, 11), date(2001, 9, 12), date(2001, 9, 13), date(2001, 9, 14),
    date(2004, 6, 11),   # President Reagan
    date(2007, 1, 2),    # President Ford
    date(2012, 10, 29), date(2012, 10, 30),  # Hurricane Sandy
    date(2018, 12, 5),   # President George H. W. Bush
    date(2025, 1, 9),    # President Carter
}


@lru_cache(maxsize=None)
def federal_holidays(year: int) -> frozenset[date]:
    days = {
        _observed(date(year, 1, 1)),
        _nth_weekday(year, 1, 0, 3),    # Martin Luther King Jr. Day
        _nth_weekday(year, 2, 0, 3),    # Washington's Birthday
        _nth_weekday(year, 5, 0, -1),   # Memorial Day
        _observed(date(year, 7, 4)),
        _nth_weekday(year, 9, 0, 1),    # Labor Day
        _nth_weekday(year, 10, 0, 2),   # Columbus Day
        _observed(date(year, 11, 11)),  # Veterans Day
        _nth_weekday(year, 11, 3, 4),   # Thanksgiving
        _observed(date(year, 12, 25)),
    }
    if year >= 2021:
        days.add(_observed(date(year, 6, 19)))  # Juneteenth, first observed 18 Jun 2021
    # New Year's Day on a Saturday is observed on 31 Dec of the year before.
    if date(year + 1, 1, 1).weekday() == 5:
        days.add(date(year, 12, 31))
    days |= {d for d in FEDERAL_EXTRA if d.year == year}
    return frozenset(days)


@lru_cache(maxsize=None)
def nyse_holidays(year: int) -> frozenset[date]:
    days = {
        _nth_weekday(year, 1, 0, 3),    # Martin Luther King Jr. Day
        _nth_weekday(year, 2, 0, 3),    # Presidents' Day
        easter(year) - timedelta(days=2),  # Good Friday
        _nth_weekday(year, 5, 0, -1),   # Memorial Day
        _observed(date(year, 7, 4)),
        _nth_weekday(year, 9, 0, 1),    # Labor Day
        _nth_weekday(year, 11, 3, 4),   # Thanksgiving
        _observed(date(year, 12, 25)),
    }
    # NYSE does not close on Friday 31 Dec when New Year's Day is a Saturday.
    new_year = date(year, 1, 1)
    if new_year.weekday() != 5:
        days.add(_observed(new_year))
    if year >= 2022:
        days.add(_observed(date(year, 6, 19)))  # Juneteenth, NYSE from 2022
    days |= {d for d in NYSE_EXTRA if d.year == year}
    return frozenset(days)


class Calendar:
    def __init__(self, name: str, holidays):
        self.name = name
        self._holidays = holidays

    def is_business_day(self, d: date) -> bool:
        return d.weekday() < 5 and d not in self._holidays(d.year)

    def business_days_between(self, start: date, end: date) -> int:
        """Business days in (start, end]: 0 for the same day, negative if end < start.

        A trade on Monday filed on Wednesday is 2 days; one on Friday filed the next
        Tuesday is 2 days, or 1 if that Monday was a holiday.
        """
        if end < start:
            return -self.business_days_between(end, start)
        # Whole weeks contribute 5 weekdays each; holidays are subtracted after.
        days = (end - start).days
        weeks, rem = divmod(days, 7)
        count = weeks * 5
        for i in range(1, rem + 1):
            if (start + timedelta(days=weeks * 7 + i)).weekday() < 5:
                count += 1
        for year in range(start.year, end.year + 1):
            count -= sum(
                1 for h in self._holidays(year) if start < h <= end and h.weekday() < 5
            )
        return count

    def on_or_before(self, d: date) -> date:
        """The latest business day not after d."""
        while not self.is_business_day(d):
            d -= timedelta(days=1)
        return d

    def add(self, d: date, n: int) -> date:
        """Move n business days forward from d (n >= 0); d itself need not be one."""
        while n > 0:
            d += timedelta(days=1)
            if self.is_business_day(d):
                n -= 1
        return d


SEC = Calendar("sec", federal_holidays)
NYSE = Calendar("nyse", nyse_holidays)
